//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.09 at 04:14:08 PM IST 
//


package com.shopdirect.ws.xsd.accountstatus;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import com.fasterxml.jackson.annotation.JsonProperty;


/**
 * <p>Java class for CustomerAccountStatus complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CustomerAccountStatus">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AccountNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CustStatusDetails" type="{http://ws.shopdirect.com/xsd/AccountStatus}CustStatusDetails" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="AccountStatusRecommendations" type="{http://ws.shopdirect.com/xsd/AccountStatus}AccountStatusRecommendations" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CustomerAccountStatus", propOrder = {
    "accountNumber",
    "custStatusDetails",
    "accountStatusRecommendations"
})
public class CustomerAccountStatus {

    @XmlElement(name = "AccountNumber", required = true)
    protected String accountNumber;
    @XmlElement(name = "CustStatusDetails")
    protected List<CustStatusDetails> custStatusDetails;
    @XmlElement(name = "AccountStatusRecommendations")
    protected List<AccountStatusRecommendations> accountStatusRecommendations;

    /**
     * Gets the value of the accountNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @JsonProperty("AccountNumber")
    public String getAccountNumber() {
        return accountNumber;
    }

    /**
     * Sets the value of the accountNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountNumber(String value) {
        this.accountNumber = value;
    }

    /**
     * Gets the value of the custStatusDetails property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the custStatusDetails property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCustStatusDetails().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CustStatusDetails }
     * 
     * 
     */
    @JsonProperty("CustStatusDetails")
    public List<CustStatusDetails> getCustStatusDetails() {
        if (custStatusDetails == null) {
            custStatusDetails = new ArrayList<CustStatusDetails>();
        }
        return this.custStatusDetails;
    }

    /**
     * Gets the value of the accountStatusRecommendations property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the accountStatusRecommendations property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAccountStatusRecommendations().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AccountStatusRecommendations }
     * 
     * 
     */
    @JsonProperty("AccountStatusRecommendations")
    public List<AccountStatusRecommendations> getAccountStatusRecommendations() {
        if (accountStatusRecommendations == null) {
            accountStatusRecommendations = new ArrayList<AccountStatusRecommendations>();
        }
        return this.accountStatusRecommendations;
    }

}
