//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.09 at 04:14:08 PM IST 
//


package com.shopdirect.ws.xsd.accountstatus;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.shopdirect.ws.xsd.accountstatus package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _GetCustomerAccountStatus_QNAME = new QName("http://ws.shopdirect.com/xsd/AccountStatus", "getCustomerAccountStatus");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.shopdirect.ws.xsd.accountstatus
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GeneralApplicationFault }
     * 
     */
    public GeneralApplicationFault createGeneralApplicationFault() {
        return new GeneralApplicationFault();
    }

    /**
     * Create an instance of {@link GetCustomerAccountStatus }
     * 
     */
    public GetCustomerAccountStatus createGetCustomerAccountStatus() {
        return new GetCustomerAccountStatus();
    }

    /**
     * Create an instance of {@link GetCustomerAccountStatusResponse }
     * 
     */
    public GetCustomerAccountStatusResponse createGetCustomerAccountStatusResponse() {
        return new GetCustomerAccountStatusResponse();
    }

    /**
     * Create an instance of {@link CustomerAccountStatus }
     * 
     */
    public CustomerAccountStatus createCustomerAccountStatus() {
        return new CustomerAccountStatus();
    }

    /**
     * Create an instance of {@link CustStatusDetails }
     * 
     */
    public CustStatusDetails createCustStatusDetails() {
        return new CustStatusDetails();
    }

    /**
     * Create an instance of {@link AccountStatusType }
     * 
     */
    public AccountStatusType createAccountStatusType() {
        return new AccountStatusType();
    }

    /**
     * Create an instance of {@link HeaderInformation }
     * 
     */
    public HeaderInformation createHeaderInformation() {
        return new HeaderInformation();
    }

    /**
     * Create an instance of {@link AccountStatusRecommendations }
     * 
     */
    public AccountStatusRecommendations createAccountStatusRecommendations() {
        return new AccountStatusRecommendations();
    }

    /**
     * Create an instance of {@link CustomerDetail }
     * 
     */
    public CustomerDetail createCustomerDetail() {
        return new CustomerDetail();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetCustomerAccountStatus }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.shopdirect.com/xsd/AccountStatus", name = "getCustomerAccountStatus")
    public JAXBElement<GetCustomerAccountStatus> createGetCustomerAccountStatus(GetCustomerAccountStatus value) {
        return new JAXBElement<GetCustomerAccountStatus>(_GetCustomerAccountStatus_QNAME, GetCustomerAccountStatus.class, null, value);
    }

}
