//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.09 at 04:14:08 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://ws.shopdirect.com/xsd/AccountStatus", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.shopdirect.ws.xsd.accountstatus;
